### ISSUE TITLE
Practica 7 - juicio experto

### ISSUE THREAD

**Issue by Heidi-19** [SistemasTecTlaxiaco/actividad-7-juicio-experto-y-costos-equipo-promastergamer777#1]

**Comment by FedericoVictorianoSierra** [comment]
[Práctica 7 Costos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-juicio-experto-y-costos-equipo-promastergamer777/files/13271812/Practica.7.Costos.pdf)

**Comment by Heidi-19** [comment]
[Práctica 7 Costos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-juicio-experto-y-costos-equipo-promastergamer777/files/13271843/Practica.7.Costos.pdf)

**Comment by JoseABCruz** [comment]
[Práctica 7 Costos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-juicio-experto-y-costos-equipo-promastergamer777/files/13272193/Practica.7.Costos.pdf)

**Comment by Aricel117** [comment]
Calificación: 30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
